name: Examples
on: push
jobs:
  nixbuild-net:
    uses: nixbuild/nixbuild-action/.github/workflows/ci-workflow.yml@v12
    secrets:
      nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
  nix-develop:
    name: "develop"
      strategy:
      matrix:
        target:
          - { os: 'darwin', platform: 'macos-latest', arch: 'arm64' }
          - { os: 'linux', platform: 'ubuntu-latest', arch: 'amd64' }
    runs-on: ${{ matrix.target.platform }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: paretooptimaldev
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: "nix develop"
      run: nix develop
